// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadConfig():Promise<string>;

export function SaveConfig(arg1:string):Promise<void>;

export function StartGame(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function UpdateServerInfo(arg1:string):Promise<void>;
