// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadConfig() {
  return window['go']['main']['App']['ReadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartGame(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartGame'](arg1, arg2, arg3, arg4);
}

export function UpdateServerInfo(arg1) {
  return window['go']['main']['App']['UpdateServerInfo'](arg1);
}
